# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_remove_failure_match'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE `failure_line` DROP COLUMN `best_classification_id`, `best_is_verified`;')
    ]
